- id: doi:10.1029/2019JC015738
  type: paper
  description: 
  date: 2020-12-4
  buttons:
    - type: data
      link: https://www.star.nesdis.noaa.gov/socd/lsa/SeaIce/SummerMeltClassification.php
    - type: source
      text: Manuscript Source
      link: https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2019JC015738
    - type: code
      link: https://github.com/ellenbuckley/MeltEvolution
  tags:
    - open science
    - collaboration
  repo: ellenbuckley/MeltEvolution


