name: build-site
run-name: build live site

on:
  # Run when called from another workflow
  workflow_call:

  # Run if user manually requests it
  workflow_dispatch:

# Variables
env:
  PREVIEWS_FOLDER: preview

permissions:
  contents: write

jobs:
  build-site:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository contents
      - name: Checkout branch contents
        uses: actions/checkout@v4

      # Install Ruby and dependencies
      - name: Install Ruby packages
        uses: ruby/setup-ruby@v1.172.0
        with:
          ruby-version: "3.1"
          bundler-cache: true

      # Configure GitHub Pages URL
      - name: Get Pages url
        id: pages
        uses: actions/configure-pages@v4

      # Append the URL to the Jekyll configuration
      - name: Set root url
        run: |
          printf "\n\nurl: ${{ steps.pages.outputs.origin }}" >> _config.yaml

      # Build the Jekyll site
      - name: Build live version of site
        run: |
          JEKYLL_ENV=production bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path || '' }}"

      # Deploy site to GitHub Pages
      - name: Commit live site to Pages branch
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          folder: _site
          clean-exclude: ${{ env.PREVIEWS_FOLDER }}
          force: false
