name: build-site
run-name: build live site

on:
  # Run when called from another workflow
  workflow_call:

  # Run if user manually requests it
  workflow_dispatch:

# Variables
env:
  PREVIEWS_FOLDER: preview

permissions:
  contents: write

jobs:
  build-site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch contents
        uses: actions/checkout@v4

      - name: Install Ruby manually
        run: |
          sudo apt-get update
          sudo apt-get install -y curl git autoconf bison build-essential libssl-dev libyaml-dev libreadline-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm6 libgdbm-dev
          curl -fsSL https://github.com/rbenv/ruby-build/archive/master.tar.gz | tar -xzC /tmp
          sudo PREFIX=/usr/local /tmp/ruby-build-master/install.sh
          sudo ruby-build 3.1.4 /opt/hostedtoolcache/Ruby/3.1.4/x64
          sudo touch /opt/hostedtoolcache/Ruby/3.1.4/x64.complete

      - name: Install Bundler and Dependencies
        run: |
          export GEM_HOME=$(pwd)/.gem
          export PATH="$GEM_HOME/bin:$PATH"
          gem install bundler
          bundle install

  

      - name: Build live version of site
        run: |
          export GEM_HOME=$(pwd)/.gem
          export PATH="$GEM_HOME/bin:$PATH"
          JEKYLL_ENV=production bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path || '' }}"
    
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          folder: _site
